language: ruby
dist: disco
sudo: required
rvm:
  # - 2.5
  - 2.7
env:
  global:
  - VAGRANT_VERSION="2.2.6"
services:
  - docker
before_install:
  - sudo apt-get -qq update
  - curl -o vagrant.zip https://releases.hashicorp.com/vagrant/${VAGRANT_VERSION}/vagrant_${VAGRANT_VERSION}_linux_amd64.zip && unzip -d bin vagrant.zip
  - PATH=$(pwd)/bin:$PATH
  - vagrant version
jobs:
  include:
    - stage: vagrant validate
      before_script: skip
      script:
        - gem install bundler #Install Bundler
        - bundle install #Install Required Gems
        - gem list #gem list
        - PATH=$(pwd)/bin:$PATH bundle exec rake vagrant:validate
        - PATH=$(pwd)/bin:$PATH bundle exec rake --tasks
    - stage: build_base
      script: sudo make build_base
    - stage: build_env
      script: sudo make build_base
    - stage: build_openjdk11
      script: sudo make build_openjdk11
    - stage: build_tomcat9030
      script: sudo make build_tomcat9030
    - stage: config_admin
      script: sudo make config_admin
    - stage: deploy_sampleapp
      script: sudo make deploy_sampleapp
    - stage: build_finalize
      script:
      - sudo make build_finalize
    - stage: test sampleapp
      script:
      - sudo make run_sampleapp
      - curl http://localhost:8080/SampleWebapp
    - stage: build_all
      script:
      - sudo make build_all
      - sudo docker image ls
after_success:
    - stage: Finalize
      script: sudo docker image ls
notifications:
  #email: false
   email:
     on_success: never # default: change
     on_failure: always # default: always
   webhooks: https://galaxy.ansible.com/api/v1/notifications/
