language: ruby
dist: disco
sudo: required
rvm:
  - 2.5
env:
  global:
  - VAGRANT_VERSION="2.2.6"
services:
  - docker
before_install:
  - sudo apt-get -qq update
  - curl -o vagrant.zip https://releases.hashicorp.com/vagrant/${VAGRANT_VERSION}/vagrant_${VAGRANT_VERSION}_linux_amd64.zip && unzip -d bin vagrant.zip
  - PATH=$(pwd)/bin:$PATH
  - vagrant version

jobs:
  include:
    - stage: Vagrant validate
      before_script:
        - sudo bundler install
      script:
        - PATH=$(pwd)/bin:$PATH bundle exec rake
        - PATH=$(pwd)/bin:$PATH bundle exec rake vagrant:validate
        - PATH=$(pwd)/bin:$PATH bundle exec rake --tasks

after_success:
    - stage: Continuous Deployment Step, one button to deploy docker image
      script: skip

notifications:
  #email: false
   email:
     on_success: never # default: change
     on_failure: always # default: always
   webhooks: https://galaxy.ansible.com/api/v1/notifications/
